backend:
  name: git-gateway
  branch: master

# allows for editing / approval of published content
# publish_mode: editorial_workflow

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: 'projects'
    label: 'Projects'
    format: 'json'
    folder: 'assets/content/projects'
    create: true
    slug: '{{uuid}}-{{slug}}'
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: "Active", name: "active", widget: "boolean", default: true, required: false}
      - { label: "Priority", name: "priority", widget: "number", default: null, required: false}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Type', name: 'type', widget: 'string' }
      - { label: 'Url', name: 'url', widget: 'string', required: false }
      - { label: 'Tech', name: 'tech', widget: 'list'}
      - { 
          label: 'Logo', 
          name: 'logo', 
          widget: 'image', 
          required: false,
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - { 
          label: 'Featured Images', 
          name: 'featured_images', 
          widget: 'image', 
          required: false,
          media_library: {
            config: {
              multiple: true
            }
          }
        }